2021-06-04 15:39:57,943 INFO    MainThread:9564 [wandb_setup.py:_flush():69] setting env: {}
2021-06-04 15:39:57,943 INFO    MainThread:9564 [wandb_setup.py:_flush():69] setting login settings: {}
2021-06-04 15:39:57,943 INFO    MainThread:9564 [wandb_setup.py:_flush():69] setting login settings: {}
2021-06-04 15:39:57,943 INFO    MainThread:9564 [wandb_init.py:_log_setup():336] Logging user logs to /Users/arjunbhalla/Desktop/School/Grad/Research/intrinsic-video-factorisation/wandb/run-20210604_153957-3unwkbob/logs/debug.log
2021-06-04 15:39:57,943 INFO    MainThread:9564 [wandb_init.py:_log_setup():337] Logging internal logs to /Users/arjunbhalla/Desktop/School/Grad/Research/intrinsic-video-factorisation/wandb/run-20210604_153957-3unwkbob/logs/debug-internal.log
2021-06-04 15:39:57,943 INFO    MainThread:9564 [wandb_init.py:init():369] calling init triggers
2021-06-04 15:39:57,943 INFO    MainThread:9564 [wandb_init.py:init():374] wandb.init called with sweep_config: {}
config: {}
2021-06-04 15:39:57,943 INFO    MainThread:9564 [wandb_init.py:init():418] starting backend
2021-06-04 15:39:57,944 INFO    MainThread:9564 [backend.py:_multiprocessing_setup():70] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2021-06-04 15:39:57,946 INFO    MainThread:9564 [backend.py:ensure_launched():132] starting backend process...
2021-06-04 15:39:57,951 INFO    MainThread:9564 [backend.py:ensure_launched():136] started backend process with pid: 9573
2021-06-04 15:39:57,952 INFO    MainThread:9564 [wandb_init.py:init():423] backend started and connected
2021-06-04 15:39:57,956 INFO    MainThread:9564 [wandb_init.py:init():465] updated telemetry
2021-06-04 15:39:57,956 INFO    MainThread:9564 [wandb_init.py:init():484] communicating current version
2021-06-04 15:39:59,595 INFO    MainThread:9564 [wandb_init.py:init():489] got version response upgrade_message: "wandb version 0.10.31 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2021-06-04 15:39:59,596 INFO    MainThread:9564 [wandb_init.py:init():497] communicating run to backend with 30 second timeout
2021-06-04 15:40:00,656 WARNING MainThread:9564 [wandb_init.py:init():764] interrupted
Traceback (most recent call last):
  File "/Users/arjunbhalla/opt/anaconda3/envs/video-factorisation/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 744, in init
    run = wi.init()
  File "/Users/arjunbhalla/opt/anaconda3/envs/video-factorisation/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 498, in init
    ret = backend.interface.communicate_run(run, timeout=30)
  File "/Users/arjunbhalla/opt/anaconda3/envs/video-factorisation/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 659, in communicate_run
    return self._communicate_run(run, timeout=timeout)
  File "/Users/arjunbhalla/opt/anaconda3/envs/video-factorisation/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 647, in _communicate_run
    resp = self._communicate(req, timeout=timeout)
  File "/Users/arjunbhalla/opt/anaconda3/envs/video-factorisation/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 537, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/Users/arjunbhalla/opt/anaconda3/envs/video-factorisation/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 82, in get
    is_set = self._object_ready.wait(timeout)
  File "/Users/arjunbhalla/opt/anaconda3/envs/video-factorisation/lib/python3.8/threading.py", line 558, in wait
    signaled = self._cond.wait(timeout)
  File "/Users/arjunbhalla/opt/anaconda3/envs/video-factorisation/lib/python3.8/threading.py", line 306, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
